### ISSUE TITLE
Question about Fig. 5 from the published paper

### ISSUE THREAD

**Issue by SoonSYJ** [IRC-SPHERE/elsts2017-temperature-data#2]
Hi, 
I have got a question about the Fig. 5: Maximum resynchronization period based on the empirical drift amplitude. 
1. As I understood that the figure is ploted based on equation (2) and node time dirft data which is showed in figure 4, how to understand the peak in Fig. 5 which should be infinity as \delta be close to 0?
2. How to understand the parameter \delta in equation (2)? For a drift value from the dataset such as "TSCH: {asn-0.c38d0 link-0-0-0-0 ch-15} drift -380", does \delta=-380 or \delta=-380 * 1024?

Thanks a lot.

**Comment by atiselsts** [comment]
@fontikos ? This one is probably for you

**Comment by fontikos** [comment]
1. It's true that if \delta was zero, the peak in Fig. 5 would get to infinity. However, Fig. 5 is based on empirical data, in which the \delta was never measured to be exactly equal to zero; it was, instead close to zero, resulting to these peaks.

2. \delta is in parts per million (ppm). The printed output should be in time units; therefore, they should be devided by the period of synchronisation to be converted in ppm.

**Comment by SoonSYJ** [comment]
Thanks a lot @fontikos @atiselsts . 
As the code in tsch-adaptive-timesync.c from ptsch said:

`last_drift_ppm = (int32_t)((int64_t)real_drift_ticks * TSCH_DRIFT_UNIT / time_delta_ticks);`
`drift_ppm = timesync_entry_add(last_drift_ppm);`
```
TSCH_LOG_ADD(tsch_log_message, 
     snprintf(log->message, sizeof(log->message),
     "drift %ld", drift_ppm / 1024));
```

I think that \delta value can be calculated just by multiplying drift value from the experimental data with 1024 ( \delta = drift * 1024). 
Is this right?

Thanks a lot.

**Comment by fontikos** [comment]
Please, see the reply below.

**Comment by atiselsts** [comment]
Hi SoonSYJ,

The code you copied is from ptsch branch. For the temperature experiments this bit in the code was actually different: the drift is printed as `"drift %ld", drift);` as it says here in the README.

The \delta value cannot be easily calculated from the experimental data unless you have the temperature compensation tables we used (which in theory we could publish). The drift that is printed is the drift *after* the temperature compensation. So we would expect this to remain small even when the nodes are heated or cooled a lot.
