### ISSUE TITLE
Question about the calculation of the "drift"

### ISSUE THREAD

**Issue by SoonSYJ** [IRC-SPHERE/elsts2017-temperature-data#3]
Hi, 
I have found the README has been updated. And what I am interested in is the "drift" value. As the README file said that 

> "drift -65 is the drift estimate of the sensor node, printed in ppm (parts per million) multiplied by 1024. I.e. -65 is approximately -0.065 parts per million".

If we look into the data (temperature_chamber_2017/node3F.txt), we can find a typical large drift value which is equal to -1747 (T_hdc = 55.74 C). Following the README, a real drift value should be approximately equal to  -1.747 ppm. Then we take a look at the Fig. 4 in the published paper and you can found a large drift value is almost -20 ppm.
So I can hardly understand this. 
Thanks a lot.

**Comment by SoonSYJ** [comment]
I have also done a chamber experiment in our Lab. The hardware used is TI's SensorTag 2.0 and the software is the raw TSCH from Contiki-OS. The drift value in the figure is just the printed value from TSCH log message which is showed in the file "tsch-adaptive-timesync.c". And our data plotted with the printed raw drift is quite similar to the data plotted in your paper (Fig. 4).
![temp_drift](https://user-images.githubusercontent.com/11547738/38532192-3c202336-3ca6-11e8-99e2-835e6a451a88.png)

**Comment by atiselsts** [comment]
Cool that you managed to get this curve!

See my reply to the #2 . Hope that clears things up. Had forgotten what exactly happens in the code myself...

**Comment by SoonSYJ** [comment]
Thanks for your help. 
So Fig. 4 is the curve of \delta. And I can not get the \delta value from the presented dataset for missing your temperature compensation table. 
Am I right?

By the way, as we have a humidity and temperature variable chamber, I have also done an experiment with the humidity varying from 30% to 90% (temperature is fixed to 30 C). The interesting thing is that the output drift is almost constant. Most of the paper have said that humidity have a effect on the clock drift which is different from the experiment result. 
Maybe you have any idea of this results? 

Thanks a lot.

**Comment by atiselsts** [comment]
That is correct. I'm not sure why would you want to reconstruct the actual drift in our results - just to repeat them in a simulator?

We haven't investigated effect from humidity, so I don't have any ideas on that.

**Comment by SoonSYJ** [comment]
Sorry for my poor English. 
Actually, I meet the problem when I try to plot Fig. 5 with our raw printed drift value from TSCH by using equation (2). 

For example: 
For equation (2), we can set 
\tau_g = 2.2ms = 2200 us
\tau_p = 160us
\delta = 256 * 20 ppm 
(20 is the raw printed drift value from TSCH and multiplied 256 to get a ppm)
Then, 
\DELTA_l = ((2200 - 2 * 160) / (2 * 256 * 20)) / 60 min = 0.003min
And we can get a curve as Fig 5 showed. 
![paireddataframe](https://user-images.githubusercontent.com/11547738/38653272-86c68f00-3e3c-11e8-9f76-633f08f0526d.png)

I think the value in the curve have a large numerical level difference from your Fig. 5. So I feel confused about the meaning and calculation of "drift" in Fig.4 and "\delta" in equation (2). 

So could you please check my calculation procedure listed above. 
Or maybe I can not get Fig. 5 just because the resolution of the drift value if too low. 

Thanks a lot.

**Comment by fontikos** [comment]
The shape looks quite similar to ours. Yet, a drift of 256*20=5120 ppm sounds very large. As you can see in Fig. 4 of our paper, we never measured a drift more than 30 ppm (in absolute terms).

**Comment by atiselsts** [comment]
You have 20 ppm drift. In public Contiki and Contiki-NG code the value is already printed in `ppm`, so there is no need to multiply:

    /* Units in which drift is stored: ppm * 256 */
    #define TSCH_DRIFT_UNIT (1000L * 1000 * 256)

So when this code is executed the result is printed in `ppm`:

    TSCH_LOG_ADD(tsch_log_message,
        snprintf(log->message, sizeof(log->message), "drift %ld", drift_ppm / 256));


And for the log files from this repository, you need to *divide* the printed drift value by 1024, not multiply, to get ppm!
